# Generated by Django 3.2.3 on 2021-06-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210616_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shouts',
            fields=[
                ('shoutId', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=250, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadDate', models.DateTimeField(verbose_name='upload_date')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
