# Generated by Django 3.2.3 on 2021-06-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouts',
            name='uploadDate',
            field=models.DateField(verbose_name='upload_date'),
        ),
    ]
