# Generated by Django 3.2.3 on 2021-06-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_shouts_uploaddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('friendId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='app.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='app.user')),
            ],
        ),
    ]
