# Generated by Django 3.2.3 on 2021-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='userId',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='userId',
            field=models.ManyToManyField(related_name='userlist_id', to='app.User'),
        ),
    ]
