# Generated by Django 3.2.3 on 2021-06-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210622_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendlist',
        ),
    ]
