# Generated by Django 3.2.3 on 2021-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('shoutId', models.ManyToManyField(to='app.Shouts')),
                ('userId', models.ManyToManyField(to='app.User')),
            ],
        ),
    ]
