# Generated by Django 3.2.3 on 2021-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210623_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='shouts',
            name='photoFileName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
