# Generated by Django 3.2.3 on 2021-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shouts_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouts',
            name='uploadDate',
            field=models.DateTimeField(verbose_name='upload_date'),
        ),
    ]
